name = "DBF"
uuid = "05a0241d-af54-46e5-a412-7f757969bf0b"
authors = ["Nick Mayhall"]
version = "1.0.0-DEV"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
PauliOperators = "be646426-f34c-4536-b1d4-a45a9633e6db"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatProfilerHTML = "a8a75453-ed82-57c9-9e16-4cd1196ecbf5"

[compat]
BenchmarkTools = "1.6.0"
JLD2 = "0.6.2"
LinearAlgebra = "1.11.0"
Optim = "1.13.2"
PauliOperators = "2.0.0"
Printf = "1.11.0"
Random = "1.11.0"
StatProfilerHTML = "1.6.0"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
